--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: 
- !ruby/object:RI::MethodSummary 
  name: define_task
comment: 
constants: []

full_name: Bundler::Deployment
includes: []

instance_methods: []

name: Deployment
superclass: Object
