--- !ruby/object:RI::ClassDescription 
attributes: 
- !ruby/object:RI::Attribute 
  comment: 
  name: root
  rw: R
class_methods: 
- !ruby/object:RI::MethodSummary 
  name: new
comment: 
constants: []

full_name: Bundler::Environment
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: current_dependencies
- !ruby/object:RI::MethodSummary 
  name: dependencies
- !ruby/object:RI::MethodSummary 
  name: index
- !ruby/object:RI::MethodSummary 
  name: inspect
- !ruby/object:RI::MethodSummary 
  name: lock
- !ruby/object:RI::MethodSummary 
  name: requested_specs
- !ruby/object:RI::MethodSummary 
  name: specs
- !ruby/object:RI::MethodSummary 
  name: update
name: Environment
superclass: Object
